spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/saasbuilder
spring.datasource.username=postgres
spring.datasource.password=Yoonus@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration
jwt.secret=mysecretkeymysecretkeymysecretkey123456

# Logging
logging.level.com.yoonus.backend.security=DEBUG